[variables]
NIXPACKS_PHP_ROOT_DIR = "/public"

[phases.setup]
nixPkgs = [
    "(php84.withExtensions (pe: pe.enabled ++ []))",
    "nginx",
    "libmysqlclient",
    "php84Packages.composer",
    "nodejs_24"
]

[phases.install]
cmds = [
    "composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev",
    "npm install"
]

[phases.build]
cmds = [
    "npm run build",

    "mkdir -p storage/framework/{sessions,views,cache}",
    "mkdir -p bootstrap/cache",

    "chmod -R 777 storage bootstrap/cache"
]