/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "index": [],
    "agendar-cita": [],
    "agendar-cita.identificar-paciente.show": [],
    "agendar-cita.identificar-paciente": [],
    "agendar-cita.paciente-nuevo.show": [],
    "agendar-cita.registrar-paciente": [],
    "agendar-cita.calendario.show": [],
    "agendar-cita.calendario.store": [],
    "agendar-cita.confirmacion": [
        {
            "name": "cita",
            "required": true,
            "binding": "id"
        }
    ],
    "agendar-cita.descargar-pdf": [
        {
            "name": "cita",
            "required": true,
            "binding": "id"
        }
    ],
    "login.show": [],
    "login": [],
    "logout": [],
    "agenda": [],
    "agenda.panel": [],
    "pacientes.seleccionar": [
        {
            "name": "idPac",
            "required": true
        }
    ],
    "pacientes.personal": [],
    "pacientes.datos": [],
    "pacientes.datos.update": [
        {
            "name": "idPac",
            "required": true
        }
    ],
    "pacientes.antecedentes": [],
    "pacientes.antecedentes.update": [
        {
            "name": "idPac",
            "required": true
        }
    ],
    "pacientes.plan_tratamiento": [],
    "pacientes.facturacion": [],
    "odontograma.index": [],
    "odontograma.store": [],
    "pacientes.index": [],
    "pacientes.regispacientes": [],
    "agenda.cita.store": [],
    "caja.facturacion": [],
    "caja.abonos.store": [],
    "caja.abonos.update": [
        {
            "name": "abono",
            "required": true,
            "binding": "id"
        }
    ],
    "caja.abonos.anular": [
        {
            "name": "abono",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.show_usuarios": [],
    "admin.registro_usuario": [],
    "admin.registro_usuario.store": [],
    "usuarios.index": [],
    "usuarios.registrar": [],
    "usuarios.detalle": [
        {
            "name": "id",
            "required": true
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
