/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "nosotros": [],
    "test": [],
    "agenda.identificacion": [],
    "agenda.verificar": [],
    "agenda.registrar_nuevo": [],
    "agenda.calendario": [],
    "citas.store": [],
    "agendar-cita": [],
    "login.show": [],
    "login": [],
    "agenda": [],
    "agenda.panel": [],
    "pacientes.seleccionar": [
        {
            "name": "idPac",
            "required": true
        }
    ],
    "pacientes.personal": [],
    "pacientes.datos": [],
    "pacientes.datos.update": [
        {
            "name": "idPac",
            "required": true
        }
    ],
    "pacientes.antecedentes": [],
    "pacientes.antecedentes.update": [
        {
            "name": "idPac",
            "required": true
        }
    ],
    "pacientes.plan_tratamiento": [],
    "pacientes.facturacion": [],
    "odontograma.index": [],
    "odontograma.store": [],
    "pacientes.index": [],
    "pacientes.regispacientes": [],
    "agenda.cita.store": [],
    "caja.facturacion": [],
    "caja.abonos.store": [],
    "caja.abonos.update": [
        {
            "name": "abono",
            "required": true,
            "binding": "id_abo"
        }
    ],
    "caja.abonos.anular": [
        {
            "name": "abono",
            "required": true,
            "binding": "id_abo"
        }
    ],
    "admin.show_usuarios": [],
    "admin.registro_usuario": [],
    "admin.registro_usuario.store": [],
    "administracion": [],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
