/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "index": [],
    "login.show": [],
    "login": [],
    "logout": [],
    "agendar-cita": [],
    "agendar-cita.identificar-paciente.show": [],
    "agendar-cita.identificar-paciente": [],
    "agendar-cita.paciente-nuevo.show": [],
    "agendar-cita.registrar-paciente": [],
    "agendar-cita.calendario.show": [],
    "agendar-cita.calendario.store": [],
    "agendar-cita.confirmacion": [
        {
            "name": "cita",
            "required": true,
            "binding": "id"
        }
    ],
    "agendar-cita.descargar-pdf": [
        {
            "name": "cita",
            "required": true,
            "binding": "id"
        }
    ],
    "agenda": [],
    "agenda.citas.confirmar": [
        {
            "name": "cita",
            "required": true,
            "binding": "id"
        }
    ],
    "agenda.citas.confirmar.update": [
        {
            "name": "cita",
            "required": true,
            "binding": "id"
        }
    ],
    "agenda.citas.cancelar": [
        {
            "name": "cita",
            "required": true,
            "binding": "id"
        }
    ],
    "usuarios": [],
    "usuarios.create": [],
    "usuarios.store": [],
    "usuarios.edit": [
        {
            "name": "user",
            "required": true
        }
    ],
    "usuarios.update": [
        {
            "name": "user",
            "required": true
        }
    ],
    "usuarios.destroy": [
        {
            "name": "user",
            "required": true
        }
    ],
    "usuarios.profile": [
        {
            "name": "user",
            "required": true
        }
    ],
    "usuarios.settings": [
        {
            "name": "user",
            "required": true
        }
    ],
    "usuarios.settings.update": [
        {
            "name": "user",
            "required": true
        }
    ],
    "pacientes.index": [],
    "pacientes.create": [],
    "pacientes.store": [],
    "pacientes.edit": [
        {
            "name": "paciente",
            "required": true,
            "binding": "id"
        }
    ],
    "pacientes.update": [
        {
            "name": "paciente",
            "required": true,
            "binding": "id"
        }
    ],
    "pacientes.destroy": [
        {
            "name": "paciente",
            "required": true,
            "binding": "id"
        }
    ],
    "pacientes.show": [
        {
            "name": "paciente",
            "required": true,
            "binding": "id"
        }
    ],
    "pacientes.verify": [
        {
            "name": "paciente",
            "required": true,
            "binding": "id"
        }
    ],
    "pacientes.historia-clinica.edit": [
        {
            "name": "paciente",
            "required": true,
            "binding": "id"
        }
    ],
    "pacientes.historia-clinica.update": [
        {
            "name": "paciente",
            "required": true,
            "binding": "id"
        }
    ],
    "pacientes.odontograma.inicial": [
        {
            "name": "paciente",
            "required": true,
            "binding": "id"
        }
    ],
    "pacientes.odontograma.final": [
        {
            "name": "paciente",
            "required": true,
            "binding": "id"
        }
    ],
    "pacientes.odontograma.guardar": [
        {
            "name": "paciente",
            "required": true,
            "binding": "id"
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
