export interface OpcionEnfermedad {
  key: string
  label: string
}

export interface PacienteExpedienteWizardForm {
  nombre: string
  apellidoPaterno: string
  apellidoMaterno: string
  fechaNacimiento: string
  sexo: 'M' | 'F' | 'O'
  ocupacion: string
  estadoCivil: string
  telefono: string
  correo: string
  estado: string
  municipio: string
  direccion: string
  religion: string
  antecedentesHereditarios: string
  alergias: string
  medicacionActual: string
  nombreMedico: string
  telefonoMedico: string
  enfermedades: string[]
  detalleOtrasEnfermedades: string
  consumeTabaco: boolean
  consumeAlcohol: boolean
  consumeDrogas: boolean
  frecuenciaConsumo: string
  grupoSanguineo: string
  embarazo: boolean
  tiempoGestacion: string
  lactancia: boolean
  mesesBebe: string
  actividadFisica: string
  calidadDieta: string
  calidadHigiene: string
  tuvoCirugiaOHospitalizacion: boolean
  detalleCirugiaOHospitalizacion: string
  padecimientoActual: string
  interrogatorioSistemas: string
  resultadosLaboratorio: string
  ultimaRevisionDental: string
  motivoUltimaVisitaDental: string
  usaAuxiliaresLimpiezaBucal: boolean
  detalleAuxiliaresLimpiezaBucal: string
  frecuenciaCepillado: string
  recibioAnestesiaLocal: boolean
  complicacionAnestesia: boolean
  detalleComplicacionAnestesia: string
  usoRemedioCasero: boolean
  detalleRemedioCasero: string
  dolorAlMasticar: boolean
  detalleDolorAlMasticar: string
  sangradoOInflamacion: boolean
  detalleSangradoOInflamacion: string
  ulcerasOrales: boolean
  frecuenciaUlcerasOrales: string
  habitosOrales: boolean
  detalleHabitosOrales: string
  malestarAbrirBocas: boolean
  malestarMovimientoLateral: boolean
  chasquidosCrepitaciones: boolean
  desviacionMandibula: boolean
  tejidosBlandosDuros: string
}

export function createDefaultPacienteExpedienteWizardForm(): PacienteExpedienteWizardForm {
  return {
    nombre: '',
    apellidoPaterno: '',
    apellidoMaterno: '',
    fechaNacimiento: '',
    sexo: 'M',
    ocupacion: '',
    estadoCivil: '',
    telefono: '',
    correo: '',
    estado: 'Tabasco',
    municipio: 'Macuspana',
    direccion: '',
    religion: '',
    antecedentesHereditarios: '',
    alergias: '',
    medicacionActual: '',
    nombreMedico: '',
    telefonoMedico: '',
    enfermedades: [],
    detalleOtrasEnfermedades: '',
    consumeTabaco: false,
    consumeAlcohol: false,
    consumeDrogas: false,
    frecuenciaConsumo: '',
    grupoSanguineo: '',
    embarazo: false,
    tiempoGestacion: '',
    lactancia: false,
    mesesBebe: '',
    actividadFisica: '',
    calidadDieta: 'Buena',
    calidadHigiene: 'Buena',
    tuvoCirugiaOHospitalizacion: false,
    detalleCirugiaOHospitalizacion: '',
    padecimientoActual: '',
    interrogatorioSistemas: '',
    resultadosLaboratorio: '',
    ultimaRevisionDental: '',
    motivoUltimaVisitaDental: '',
    usaAuxiliaresLimpiezaBucal: false,
    detalleAuxiliaresLimpiezaBucal: '',
    frecuenciaCepillado: '',
    recibioAnestesiaLocal: false,
    complicacionAnestesia: false,
    detalleComplicacionAnestesia: '',
    usoRemedioCasero: false,
    detalleRemedioCasero: '',
    dolorAlMasticar: false,
    detalleDolorAlMasticar: '',
    sangradoOInflamacion: false,
    detalleSangradoOInflamacion: '',
    ulcerasOrales: false,
    frecuenciaUlcerasOrales: '',
    habitosOrales: false,
    detalleHabitosOrales: '',
    malestarAbrirBocas: false,
    malestarMovimientoLateral: false,
    chasquidosCrepitaciones: false,
    desviacionMandibula: false,
    tejidosBlandosDuros: '',
  }
}
